label frenzyroute:
mcn "I think...I'm gonna go with the House of Frenzy!"
swa "Damn okay! Maybe you're new drag name should be Miss Wasted Potential. SMH."
cup "It's okay, this just means we'll have to be enemies to lovers, [mcn]~"
"Venus gives them a look and shoos them away."
swa "See you around, [mcn]."
nar "Cupid winks and and blows you a kiss before waving goodbye."
nar "The two walk away with a flounce that you can't help but feel was a little personal."
nar "Venus smiles sweetly at you and grabs both of your hands in hers."
nar "You freeze a bit from how sudden the contact was, but something about her motherly aura compells you into calmness."
ven "Welcome abroad! I know it's getting pretty late-- I'm so sorry for keeping you up."
ven "Get some rest and take care, okay?"
nar "She's soft and warm to hug. Slim-framed, but toned and soft."
nar "She gives you her number before leaving."
ven "Remember to call me, [mcn]!"
stop music
## black screen. maybe day counter? idk
label skate:
scene bg cd1
nar "She texted you an address, and told you to meet her there on Saturday morning. And, for some reason, she told you not to eat breakfast...?"
nar "You show up early."
nar "Like maybe forty five minutes early."
nar "You don't really trust the NYC subway system to run on time."
nar "It's a lot of distrust. The kind of distrust that makes you at *least* half an hour early to everything."
nar "You walk up the subway stairs and turn the corner, eyes glued to the Google Map displayed on your phone..."
nar "...and look up to find you're in front of..."
mcn "a Roller Rink?"
mcn "Wha-- Why are you here?!"
mcn "You thought you two were practicing voguing! And, isn't this a little too, ah... public?"
nar "Venus is, miracuslouly, already there! You're glad you don't have to stand around akwardly waiting for her."
nar "You follow her inside as she taps away at her phone."
nar "She seems to be completely ignoring you as she drops her duffel bag on the bench and starts stretching"
ven "Have you ever rollerskated before?"
mcn "Uh-"
menu:
    "Yes":
        ven "Coolio, how much experience do you have? With any sort of skating?"
        menu:
            "Tech decks in middle school":
                ven "I have no idea what you're talking about."
            "Tony Hawk wishes he was me":
                ven "I don't think that man rollerskates."
                ven "But your answer tells me everything I need to know about your experience..."
            "I tried it once because Tiktok made it look easy. I quit after a week.":
                ven "Hey, that's something! At least you know some of the jargon, that's a great start."
    "No":
        ven "Well, then I'm honored to be your teacher!"
        "She dramatically bows while strapping on her blades and helmet"
        mcn "But I don't have rollerskates-"
        ven "We're renting you some blades."
        mcn "..."
        ven "Don't worry! If you get fungus foot you can use the competition money to scrub it off later."
ven "And, I did tell you about the competition, right?"
nar "... what... competition"
ven "Ah, I can see by your silence that I may have neglected to mention it."
ven "Well, there's a competition coming up next week, and I already signed you up. No need to thank me."
nar "You can feel yourself start to sweat. A competition? Next week? You need a little more warning than that!"
ven "Hey."
nar "She stands up and squeezes your shoulder."
ven "Take a deep breath. I believe in you; I wouldn't have entered you if I didn't"
nar "And by some miracle, you're able to take that deep breath, and feel yourself calm down."
nar "But only by a small margin! You are *still* sweating over this."
ven "So, do you want to watch me first or are are you itching to take the plunge?"
menu:
    "Wait. You still need a minute!":
        mcn "I'd rather just watch for now..."
        ven "Nooo problemo. Just sit back, relax, and get your stretch on while I take the rink!"
        nar "You... don't actually have a stretching routine, or even know what stretches you should be doing right now."
        nar "As you're making up some stretches, Venus finishes lacing her skates and effotlessly slips onto the smooth shiny floor of the rink."
        nar "You watch as she picks up speed, gliding across the floor and cutting through the air like a fish in the water."
        nar "She really loves this, and it's obvious in the way that you see some stress that you hadn't even noticed before roll off of her shoulders as she relaxes."
        nar "You also see her whizzing past some of the other skaters, turing to skate backwards a few times, and even sticking her tongue out at one person, who just rolls their eyes."
        nar "Just as you're running out of stretching ideas, you look up and make eye contact with Venus, who is now back at the gate she entered from."
        ven "All ready?"
        nar "You give a trepadatious nod."
    "No point in putting it off!":
        mcn "I... think that I'll take the plunge."
        ven "That's what I love to hear!"
        nar "She grins widely at you."
        ven "But you need to stretch first! It's super important. Seriously. The last time I skipped stretching I dislocated my knee."
        nar "You cringe. Yeah, stretching sounds like a good idea."
        nar "Venus sits you down and shows you a bunch of stretches. You didn't realize there were so many kinds of stretches."
        nar "After a good few minutes, she seems to think you're ready, and you both lace up your skates."
        ven "Alright, do you think you're ready?"
        nar "As she says it, she slips onto the shiny floor of the rink. Her balance is *literally* perfect, not even a wobble!"
        mcn "Uh... as ready as I'll ever be?"
nar "Venus grins at you and extends a hand to help you onto the floor."
nar "You already feel incredibly unsteady on your feet, and you know it's only about to get worse."
ven "Careful... careful... c'mon, you've got it!"
nar "She guides you onto the rink her grip firm and reassuring. While your legs shake, she feels like an anchor."
ven "See? You're doing great!"
nar "You make the mistake of moving your feel a bit too much and fall flat on your butt."
nar "Venus reaches down to help you back up."
ven "Hey, don't worry about it! I can't even count the numer of times I've fallen while skating."
nar "The cycle of falling down and being helped back up continues for a good hour."
nar "Until, suddenly, you find yourself finding your balance!"
ven "Hey, that was pretty quick!"
nar "You find yourself beaming despite the numerious faceplants in your recent past."
ven "Think you're good to skate on your own for a second?"
mcn "Just a second."
nar "Venus slowly lets go of your hands and allows you to find you freestanding balance, and..."
nar "You don't immediately fall!"
nar "You start, well, duck walking like Venus had showed you in the midst of your tragic failures."
nar "It's obviously not the same as *voguing* duck walking..."
nar "...but that had certainly been your first thought when Venus had explained it to you."
nar "in what seems like no time at all you're able to get into a slow glide."
nar "Venus skates backwards next to you as you make your way around the rink, trying to gain more familiarity with the feeling of skating."
ven "How are you feeling, [mcn]?"
mcn "Uh, still a bit wobbly?"
ven "Don't dwell on that, seriously."
ven "I don't expect you to be an olympic level skater after just a few hours!"
ven "Need any help? Have any questions?"
mcn "I guess... how is learning to roller skate going to help me vogue?"
ven "Balance. Seriously. Balance and coordination."
mcn "Yeah?"
ven "Yeah! Maybe one day, when you're as good as *me*,"
nar "Her tone is light and teasing."
ven "you'll be able to *vogue* duckwalk in your skates."
mcn "Can you really?"
ven "Yes! But... you can't really, not on the wheels. You have to walk on the brakes."
mcn "You had me so excited!"
ven "Hey! I think it's still impressive."
ven "Anything else you wanted to ask me, [mcn]?"
mcn "Well, I was curious how you started doing drag...?"
ven "Some of it's a bit heavy. Are you good for that?"
nar "You nod, and you both slow and come to a stop on your skates."
nar "As you take of your skates and start doing wrap-up stretches, she starts talking again."
ven "I came out to my family as a trans woman when I was 14."
ven "As you may have already guessed, I'm a woman outside of the ballroom..."
ven "My parents kicked me out."
ven "I was homeless for about two years."
ven "I eventually met another trans woman in a homeless shelter I was staying in."
ven "She the one who introduced me to the ballroom scene. She introduced me to skating, too."
ven "It helped me out of a... really bad place, mentally."
ven "And physically. When her drag mother took me as a daughter, she also helped me to find people to stay with and eventually get stable housing."
ven "Ballroom gave me a community, a family..."
ven "And even a roof over my head."
ven "So, I kept doing drag, and kept skating. They really help me to express myself, and to ground myself."
ven "My drag sister, the one I mentioned earlier, is a part the House of Frenzy now."
ven "She was so proud of me when she learned I was starting my own house. Insisted she be the first member."
ven "So, yeah... I became a drag mother because I want to be able to help people in the same situation I was in."
ven "People who are without homes, without communities, without hope..."
nar "She clears her throat and sniffles."
mcn "Thank you, Venus. For sharing this with me..."
menu:
    "Comfort her":
        nar "You lean towards Venus, still in her sitting position on the floor next to you, and give her a tight hug."
        nar "She lets out a long breath, and hugs you back."
        ven "Thank you, [mcn], for being a good listner. And for the hug."
        ven "I still cry like this whenever I talk about it. I don't know if there'll ever be a time that I *don't* cry..."
        mcn "I understand, Venus... it's painful. I don't think anyone would expect you to just not cry."
    "Uhh... I don't know how to comfort people!":
        nar "Venus rubs at her eyes and lets out a shaky breath."
        ven "I'm sorry... I still always cry like this when I talk about it..."
        ven "Could I... have a hug?"
        nar "Perfect, a way to comfort her that doesn't involve trying to put complicated sentiments and feelings into words."
        nar "You lean to where she's sitting and hug her, and she hugs you back, tight."
        nar "It's warm, and comforting to you, despite Venus being the one being comforted."
nar "Venus pulls back from the hug and smiles at you."
ven "Thanks, kid."
mcn "I'm *not* that much younger than you."
