label heartsroute:
mcn "House of Hearts sounds like a great offer! I'll take it."
cup "Perfect! You made the right choice, doll."
ven "A bit disappointing, but whatever. Have fun girlies!"
swa "Yeah, what a shame."
mcn "I'm sorry, it's nothing personal I-"
nar "Cupidia shushes you and pulls you close to her"
cup "First rule now that you're mine: you learn to break hearts."
cup "You're not putting them down, you're just standing up with me."
nar "You guess she's right..."
mcn "Okay...thanks?"
nar "Venus and Swanna walk out together."
cup "Now, when are you free?"
menu:
    "Like...as in a date?":
        mcn "Like...as in...?"
        cup "OH! No no no babe, as in for training,"
        cup "(But, y'know, I'm free *anytime*~)"
        nar "You can never really tell whether or not she's joking."
        nar "You kind of like the attention, even if it's a little weird."
    "Like...for training?":
        mcn "For training? Or is there something I'm missing here?"
        nar "She giggles and brushes a strand of hair behind her ear."
        cup "For training, dearie!"
        cup "But, y'know, I'm *always* free for *you*~"
mcn "Uh, I guess I'm free for training this weekend? Is it for anything specific, or...?"
cup "Oh right, so, uhh, there's a ball competition in a week or two and you're the perfect fresh blood that we need to win!"
nar "And she's just going to throw you into it?! Without asking?!"
mcn "Thanks..."
cup "I mean you stole me, Nia, and Aliyah's hearts!"
mcn "Wha-"
cup "Oh my bad, I *totally* forgot you don't know any of our day names."
cup "Venus Fly is Nia"
cup "and Swanna Song is Ali, or Aliyah. Whatever he's feeling on the day, y'know?"
mcn "Wait, what about yours?"
cup "Oh right, I'm Imani!"
cup "You can call me whatever feels best though,"
cup "I prommy I don't mind!"
mcn "Oh, good to know, thank you."
cup "But yeah, I think you're a great fit. Just a little rough around the edges! But with my help I know you'll win."
nar "You're not sure if you should feel reassured by her confidence, or insulted that she called you 'rough around the edges'"
stop music
scene bg black
with dissolve
pause(3.0)
play music subwayw
label trainingweekend:
scene bg black
nar "It's a week later, and Imani has texted you to pull up at a restaurant."
nar "You're there about 20 minutes earlier than Imani asked you to be,"
show bg asway
with dissolve
nar "The NYC subway has give you trust issues that result in a constant early streak."
nar "And, actually, you're usually 30 minutes earlier or more."
nar "The unreliability of the NYC subways gives people trust issues..."
nar "Trust issues that result in a constant streak of being early to *everything*, lest you end up being late!"
nar "You dwadle outside as you wait for Imani to show up..."
nar "It's a restaurant in lower Manhattan, near the seaside. It looks fancy."
nar "You gulp in fear. How are you going to afford all this?"
nar "You don't even know how to go in, or if you need a reservation, or if you *should* go in-"
show cup idle at right
with moveinleft
cup "First step of winning: know your worth."
nar "You almost jump out of your skin! You didn't even hear him come up behind you!"
nar "He slings his arm around your shoulders and leans in close with no preamble."
cup "I can tell you're a nervous person, [mcn]..."
cup "But you're the bomb, okay babe? So I'm taking you here so get more confidence."
mcn "I don't fully understand your method, but..."
cup "That's the spirit!"
nar "He pulls you towards the door and ushers you inside, offering you sweet nothings of reassurance along the way."
cup "I've got a reservation for two? It's under 'Davis'."
nar "You're led to a table and sat down with a pair of menus."
cup "Sooo what are you in the mood for, honey? Wine? Pasta? Soup? And don't worry about the bill, I'll cover it for ya."
nar "Well, that's a relief!"
nar "He bats his eyelashes at you as he continues to chatter, something which he does a lot."
nar "...you still can't tell if it's serious flirting or if he's just like that."
mcn "Uh, the chicken and gnocci soup looks good?"
cup "It toootaly is. You should also get the lasagna!"
mcn "Okay, I'll try it."
nar "The waiter comes back after a few more minutes of your and Imani's deliberation."
nar "The waiter asks what they can get started for you."
nar "Theres a beat of silence before Imani raises an eyebrow, and you realize he expects you to order for both of you."
mcn "Uh, the chicken gnocci soup? And, uh, the lasagna? If that's okay?"
mcn "And uh... the... chicken parmesan?"
$ siren += 2
nar "The waiter nods while writing down your order before walking away."
mcn "So... how is this supposed to make me good at... siren-ing?"
cup "First lesson, confidance is KEY, baby."
cup "I could instantly tell you're a sort of akward and anxious type of person--"
nar "Gee, thanks."
nar "But... he's certainly not wrong."
cup "--so, honestly I was kind of shocked when you said you wanted to join my house!"
cup "I'm not gonna, like, ask you to heckle them over the bill or anything, this isn't really to build your charisma."
cup "It's for your confidence! Ordering food is hard as fff--"
cup "--rick. Hard as frick and honestly you did way better than I thought you would!"
mcn "Um. Thanks."
cup "Use these interactions with resturant staff to build your self-assurance!"
cup "Also I just reeeally wanted pasta."
nar "Theres about a minute of silence as the two of you sip on iced water and eat the complimentary breadsticks."
cup "So, got any questions for me, [mcn]? I'm sure you're just bursting with them!"
mcn "Uh... I guess I was kind of curious how you go into drag?"
cup "My ex got me into it, actually."
cup "Believe it or not, I used to be preeetty butch."
nar "You can't help but raise your eyebrows in surprise."
cup "I know, I know!"
cup "He's a butch queen, and while we were dating I started going to all the competitions he performed in..."
cup "...and realized that this, that ballroom, was what I'd always been missing!"
cup "Like... even though I'd accepted myself as gay I felt like I had to be super masculine... Being around so many femme queens..."
cup "it made me realize that I could express myself and my identiy and sexuality like they did."
nar "He sniffles a little."
cup "Sorry, I always get emotional about it."
mcn "I'm so happy you found drag, and that it's so important to you, Imani."
nar "He sniffles again, and you can see his eyes watering a little."
menu:
    "Comfort him!":
        nar "You reach your hand across the table to hold his."
        nar "He startles for a second because of the suddenness, before giving you a watery smile and placing his second hand on top of the hold."
        cup "Thanks..."
        nar "A few more sniffles, and then a soft chuckle."
        cup "Is it that obvious that my love language is physical touch?"
        nar "You huff a laugh."
    "Uh... don't comfort him! You don't know how to comfort people!":
        nar "You wish you could do something, but you have no idea what to do..."
        cup "Could we like... hold hands... for a second..."
        cup "I know its weird I just... physical touch is my love language and it helps me calm down and stuff..."
        cup "If... you're okay with that?"
        nar "You wordlessly extend your hand and offer him a smile. You're glad you can comfort him like this, since you're generally awful with words..."
nar "As you're still holdng hands, the waiter returns with two plates and a bowl on their tray"
cup "Ooh yes chicken parm!"
nar "Upon seeing his food, Imani breaks the hand-hold and does a complete emotional 180. Jeez, is the chicken parm really that good?"
nar "The waiter sets Imanis food down first, and then your soup and lasagna in front of you."
nar "You immediatly notice that the lasagna seems to be... terribly burnt"
nar "Before you can say anything, the waiter pulls out their cheese grater and starts grating it over the cheese."
nar "Without even asking if you wanted any cheese."
nar "And, you did want a little cheese, so it's fine, but it's still weird!"
nar "You decide to wait until after they're done with the cheese to ask about the lasagna."
mcn "Uh, that's enough cheese, thank you."
nar "They do not stop grating the cheese."
nar "Maybe you were being too guiet?"
mcn "Uh, I'm sorry, but I said that's enough cheese on my soup?"
nar "The grating continues. The cheese pile grows higher."
mcn "Would you please stop putting the cheese on my soup? I don't want anymore..."
nar "The waiter makes direct eye contact with you and keeps grating it, until the grater... runs out of cheese."
nar "They then abruptly leave without saying anything."
nar "You stare at the over-cheesed soup and burnt lasagna, totally appaled."
mcn "Did I... do something?"
nar "Imani just shrugs and continues to eat his chicken parmesan, which he had started while the cheese fiasco was occuring."
nar "What are you supposed to do here...?"
nar "I mean, you know what they say; the customer is always wrong!"
nar "Maybe you should just shut up and eat what you were given..."
menu:
    "Eat what you were given!":
        nar "The employees are probably just having a bad day. No need to make it worse by asking for your food to be remade."
        nar "You move your soup away for a moment, you'll just use a spoon to take out the extra cheese in a minute..."
        nar "The lasagna. You pull the plate towards you and pick up your knife and fork."
        nar "The outside is like... completely burt. But the inside is probably soft and lasagna-y!"
        nar "You cut into it, and see that the inside of the lasagna is in fact..."
        nar "Also completely burn?"
        nar "How do you burn a lasagna this badly?!"
        nar "You look to Imani for guidence. He is completely entranced by the chicken parmasean and pays you no mind."
        nar "You look to your soup and see that the cheese has melted at a frankly terrifying rate. A rate that makes you wonder just how hot the soup was..."
        nar "You may have to talk to the chef after all, unless you want to go hungry..."
    "Talk to the chef!":
        nar "You can't let this stand..."
nar "You take a deep breath... okay. Just notify the chef that the lasagna is burnt! It was probably just an accident."
nar "And the cheese thing was weird, but everyone has bad days!"
mcn "I'll be right back Imani."
nar "No reply. Chicken parmasean indulgence."
nar "You get up and walk towards where you know the kitchen is, burned lasagna in hand. You then wait by the door for someone to notice you."
nar "A waiter approaches, and asks if you need some help."
mcn "Uh... yes... please? I wanted to talk to the chef about my lasagna... It's too burnt to eat."
nar "The waiter scoffs and said something about picky eaters."
mcn "Okay, I'm sorry, but the lasagna is literally compltely burnt all the way through. Like. all of it. This isn't normal? And I would like a replacement, please."
mcn "And, an explanation would be nice too."
nar "You set the plate of lasagna down walk back to your table, only to see Imani watching your every move...?"
mcn "Imani...?"
nar "He motions for you to come back to the table. You do, and then sit down. The overcheesed soup is a blight in the corner of your vision."
cup "Guess what!"
cup "I'm actually friends with some of the staff and asked them to pull shit like that on us to build your confidence!"
cup "Surprise!"
nar "Despite the stress of all of that... you just find yourself laughing. Probably with relief that this burnt lasagna wasn't an actual attack on your life."
nar "It's so ridiculous. Who would think this up?"
nar "Imani, you suppose. He's definatly fun, that's for sure."
cup "Do you mind if they come over and eat with us? I prommy they'll make your food right this time!"
mcn "Yeah, I can't wait to hear how much laughter they were holding back."
nar "They bring out your food, and it's made correctly this time. The lasagna is pretty good."
nar "And as it turns out, two of them are also members of the House of Heart!"
nar "As well as general chatter, they share plenty of ballroom tips with you over the soups and pastas."
cup "Don't loose my number! You can meet even more of us when you do more training with me, alright?"
cup "I'll call you!"
