label mirrorsroute:
# nar "swannas tailor they get fitted for some fancy shit"
# nar "and then they go to pruchel; the combonation prada, gucci, and channel."
# nar "imagine a combonation pizza hut/taco bell but instead is high end fashion!"
#mcn "..."
# swa "to be fair, you have to have a very high IQ to understand the pruchel aesthetic and message."
mcn "I... think that I want to join the House of Mirrors!"
swa "You made the right choice, darling. You will *not* regret this."
nar "Her talk about billboards might've gotten to you a little, in a good way."
nar "Is that something that could really be in the cards for you? You feel your stomach flip."
cup "We could've had something special!"
cup "Perhaps... a forbidden romance between lovers from rival factions is oncoming?"
cup "Are we doomed to forever be serperated by this division? Or will love find a way?!"
nar "Venus rolls her eyes."
ven "Cut it out, Cupid."
ven "I'd have liked for you to choose me, but I know Swanna will take care of you. Have fun, kid."
nar "As they leave, Cupidia blows you a kiss and winks."
nar "Swanna huffs a laugh and rolls her eyes."
swa "[mcn], I'm thrilled to have you in my thrall."
nar "She brandishes a pen out of who knows where and writes down a name and phone number."
mcn "Ali Harris?"
swa "Ah, yes. That's my day name. Ali *or* Aliyah, that is, depending on the day."
nar "She dissapears the pen and taps your hand."
swa "Give me a call when you get the chance, wouldn't you dear?"
stop music
###
nar "A week later, you're standing in front of a very fancy looking building at an address texted to you by Swanna."
nar "She had asked you to meet here, well... not for another 30 minutes."
nar "The NYC subway system has given you trust issues that pretty much result in you being at least half an hour early to everything, lest you be late."
nar "As you continue to loiter, the door of the building suddenly swings open to reveal Swanna!"
swa "[mcn], I'm thrilled to see you! And you're early, even. Come in, come in..."
mcn "Hi, Swanna! I'm really excited to be... wherever we are?"
swa "I didn't tell you?"
mcn "No, you just texted me the address and told me to get here at nine in the morning."
swa "Well, then why don't you look around and see if you can take a guess."
nar "You look around."
nar "You see bolts of cloth, cloth manequins, needles and thread, and a three-fold mirror, among other things."
mcn "A... tailor shop?"
swa "Not just *a* tailor show, darling. *My* tailor shop!"
mcn "Wow! You own a tailor shop? Really?"
swa "Indeed I do. I have a personal tailor of course, but he mainly works *with* me rather than just *for* me, you know?"
swa "I design all of my own dresses here. Beautiful, is it not?"
mcn "It really is... wow..."
mcn "So... what are you going to have me do today?"
swa "I am going to take your measurments to start on a custom garment for you, my dear."
nar "Your eyes widen."
mcn "Wow, really? Oh my gosh!"
swa "I never let any of my daughters perform or compete in clothes that I don't think are perfect for them."
swa "There's a competition coming up, and I would like to enter you in it."
swa "Or, rather, I already have entered you into it. And am telling you about it only now."
nar "She... entered you in a drag show without asking? You, with such little expierence?"
nar "You feel a bit faint."
nar "But if it happens, Swanna seems like the type to own one of those fancy fainting couches, so you'll probably be fine."
nar "Well. You suppose at least it's a vote of confidence from Swanna, that she thinks you won't totally bomb this show..."
mcn "Uh... thank you?"
swa "You're quite welcome. Now get over here so I can take your measurments."
nar "You stand in front of the three-fold mirror and imagine yourself in one of the elegant dresses that are on the many manequins."
nar "You feel giddy with anticipation!"
mcn "So, Swanna, what got you into drag? If you don't mind me asking, that is..."
swa "You can call me Aliyah today if you prefer, dear."
swa "And, well... I started attending balls when I was around the age of 20."
swa "It was a place I've always felt very... welcomed."
swa "One of the mothers who I frequently attended the same balls that I did eventually started talking to me. Asking me about myself."
swa "And made me realize that ballroom is what I wanted to do."
swa "I had no family after I came out. My parents didn't want anything to do with me."
swa "And drag changed that. I became a mother when I was 23, hoping to do for others what my mother did for me."
nar "You feel yourself tear up a little."
mcn "Thank you, Aliyah. For sharing that with me... and for taking me as your daughter."
nar "You think you hear a sniff from Swanna as well."
swa "You're very welcome, darling."
swa "And, you can step down now. I'm done taking your measurments."
nar "You step down and watch as Aliyah scribbles neatly in a little book. The cover reads simply, House of Mirrors"
swa "Alright. Now, I'm going to give you a sort of test."
mcn "Uh, was I supposed to study for this?"
nar "You don't remember being told about a test!"
swa "No, this is a pop quiz! More of an assessment, really."
nar "She leads you to a large vanity with a hollywood style mirror."
swa "I want you to beat your face, as best you can."
menu:
    "You want me to punch myself?":
        mcn "You want me to punch myself...?!"
        swa "Well, I suppose that does a bit tells me how much you know about makeup."
        swa "No, dear. It's slang. I want you to do a full face of makeup for me."
        nar "You feel your face flush in embarassment."
        mcn "Oh. Yeah, that makes sense."
    "I'm not very expierenced with makeup":
        mcn "I'm not super expierenced with makeup... I don't know if I'll do to well."
        swa "Well, at least you know what a beat face is, darling. There are those who come in without even knowing *that*."
        nar "This makes you feel a bit better about your makeup skills."
    "I know a little about makeup.":
        mcn "I do know a little about makeup, so, hopefully I'll at least look *okay*..."
        swa "Have more confidence in your skills! I'm sure you'll do wonderfully."
swa "Now, go on ahead. All of the makeup will be in the righthand drawers."
swa "And take your time, dear. Good things come to those who... take their time?"
swa "As I said it I realized that the original saying doesn't completely make sense, but you know what I mean."
